development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: ohmyxin_development
  pool:     5
  username: postgres
  password: postgres
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: ohmyxin_test
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  host:     <%= Rails.application.credentials.dig :postgres, :host %>
  encoding: unicode
  database: <%= Rails.application.credentials.dig :postgres, :database %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 16 } %>
  username: <%= Rails.application.credentials.dig :postgres, :username %>
  password: <%= Rails.application.credentials.dig :postgres, :password %>
  template: template0
